version: '3.8'

services:
  # Сервис бд
  db:
    image: postgres:15-alpine
    container_name: currency-rate-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5437:5432" # Хост:Контейнер.
    # Тома (volumes) для сохранения данных БД между перезапусками
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Сервис
  app:
    build: .
    container_name: currency-rate-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      GIPHY_API_KEY: ${GIPHY_API_KEY}
      EXCHANGERATE_API_KEY: ${EXCHANGERATE_API_KEY}

    # Приложение должно запускаться только после того, как БД будет готова
    depends_on:
      - db
    networks:
      - app-network

# Определяем том для хранения данных БД
volumes:
  postgres_data:

# Определяем сеть для связи контейнеров
networks:
  app-network:
    driver: bridge
