spring:
  application:
    name: currency-rate-gif-selection-app

spring.datasource:
  url: jdbc:postgresql://localhost:5437/postgres
  username: postgres
  password: ${POSTGRES_PASSWORD} # задать в Run Configuration: r...
#  driver-class-name: org.postgresql.Driver

spring.liquibase:
  change-log: classpath:/db/changelog/changelog-master.yml
  enabled: true

spring.jpa:
  hibernate.ddl-auto: update
  show-sql: true

external-giphy:
  api-key: ${GIPHY_API_KEY} # задать в Run Configuration: sD79...
  url: https://api.giphy.com/v1/gifs/search
  search-word:
    positive-rate: rich
    negative-rate: broke
  search-limit: 100 # Лимит на количество гифок, которые можно получить за один запрос.

external-exchangerate:
  url: https://v6.exchangerate-api.com/v6/${EXCHANGERATE_API_KEY}/latest # задать в Run Configuration: eafb...