spring:
  application:
    name: currency-rate-gif-selection-app

  datasource:
    url: jdbc:postgresql://localhost:5437/postgres
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml
    enabled: true

  jpa:
    hibernate.ddl-auto: none
    show-sql: true

external-giphy:
  api-key: ${GIPHY_API_KEY} # задать в Run Configuration: sD79...
  url: https://api.giphy.com/v1/gifs/search
  search-word:
    positive-rate: rich
    negative-rate: broke
  search-limit: 25 # Лимит на количество гифок, которые можно получить за один запрос (max = 50, ограничено Giphy API).

external-exchangerate:
  url: https://v6.exchangerate-api.com/v6/${EXCHANGERATE_API_KEY}/latest # задать в Run Configuration: eafb...

logging:
  level:
    root: INFO
    ru.yandex.kingartaved.currencyrategifselectionapp.data.repository: DEBUG
    ru.yandex.kingartaved.currencyrategifselectionapp.service: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

#feign:
#  client:
#    config:
#      default:  # Для всех Feign клиентов
#        loggerLevel: full

#debug: true
